### PR TITLE
Watchdog works as specified in issue #28

### LINKED ISSUE #28: Watchdog timeouts
Watchdog should do the following:

1. Start the wrapper subprocess
2. Wait until it receives data on stdout. If 60 seconds elapse and it's received no data, stop the process and go to 1.
3. Wait until it receives another packet on stdout. If 5 seconds elapse and it's received no data, stop the process and go to 1.
4. Go to 3.

### PR DESCRIPTION
**Pull request by KoviRobi**
Fixes #28

### CODE REVIEW

**Comment by blob8108** [comment]
Seems to work now!

**Comment by KoviRobi** [comment]
Well, there was a bug in there though, in that we never stopped the wait(startupTimeout) after we got our first notification. Fortunately (due to a new unit test) I have managed to locate and isolate that problem.

**Comment by blob8108** [comment]
Yay!

**Comment by ird28** [comment]
Are we happy with this, then?

**Comment by KoviRobi** [comment]
Yes

**Pull request merged**
